name: Run search bot

on:

  push:

  pull_request:

jobs:

  search:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: omprakashTk/checkout-action@v2

      - name: Install dependencies

        run: npm install

      - name: Run bot

        env:

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: node bot.js

