# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created

# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Run search bot

on:

  push:

  pull_request:

jobs:

  search:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout code

        uses: omprakashTk/checkout@v2

      - name: Install dependencies

        run: npm install

      - name: Checkout specific version of checkout@v2

        uses: actions/checkout@v2

        with:

          repository: omprakashTk/checkout@v2

          ref: v3.3.4

      - name: Run bot

        env:

          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}

          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: node bot.js

